from typing import List, Optional, Protocol
from uuid import UUID

from .dto import UserDTO


class IUserReader(Protocol):
    async def list_all(self, exclude_person_id: UUID, include_deleted: bool = True) -> List[UserDTO]: ...
    async def get_by_id(self, person_id: UUID) -> Optional[UserDTO]: ...
    async def get_by_email(self, email: str) -> Optional[UserDTO]: ...

class IUserWriter(Protocol):
    async def create(self, *, first_name: str, last_name: str, email: str, role_id: UUID) -> UserDTO: ...
    async def email_exists(self, email: str) -> bool: ...
    async def soft_delete(self, person_id: UUID) -> bool: ...
    