"""db(migrations): remove unused table and define unique constraints

Revision ID: 0125a9c6b159
Revises: 34b91500812a
Create Date: 2025-06-29 01:33:30.212552

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0125a9c6b159'
down_revision: Union[str, None] = '34b91500812a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    op.add_column('persons', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'persons', ['national_id_number'])
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'persons', type_='unique')
    op.drop_column('persons', 'is_deleted')
    op.create_table('user_permissions',
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('GRANT', 'DENY', name='permission_type_enum'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name=op.f('user_permissions_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['users.person_id'], name=op.f('user_permissions_person_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'permission_id', name=op.f('user_permissions_pkey'))
    )
    # ### end Alembic commands ###
