"""db(migrations): add type field to educational_institutions for status management

Revision ID: 1f88221841d6
Revises: f79409d27c59
Create Date: 2025-09-01 08:40:16.258292

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f88221841d6'
down_revision: Union[str, None] = 'f79409d27c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum(
    "AFFILIATED", "UNAFFILIATED", "SANCTIONED",
    name="institution_status_type_enum",
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    status_enum.create(bind, checkfirst=True)
    op.add_column('educational_institutions', sa.Column('status', status_enum, nullable=True))
    op.add_column('educational_institutions', sa.Column('occurred_at', sa.Date(), nullable=True))
    op.execute("""
        UPDATE educational_institutions
        SET status = CASE
            WHEN is_sanctioned THEN 'SANCTIONED'
            WHEN is_affiliated THEN 'AFFILIATED'
            ELSE 'UNAFFILIATED'::institution_status_type_enum
        END
    """)
    op.alter_column("educational_institutions", "status", nullable=False)
    op.drop_column('educational_institutions', 'is_affiliated')
    op.drop_column('educational_institutions', 'is_sanctioned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.add_column(
        "educational_institutions",
        sa.Column("is_sanctioned", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "educational_institutions",
        sa.Column("is_affiliated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.execute("""
        UPDATE educational_institutions
        SET
            is_sanctioned = (status = 'SANCTIONED'::institution_status_type_enum),
            is_affiliated = (status = 'AFFILIATED'::institution_status_type_enum)
    """)
    op.drop_column("educational_institutions", "occurred_at")
    op.drop_column("educational_institutions", "status")
    status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
