"""db(migrations): rename ID column in representatives table

Revision ID: 295f5807dda5
Revises: 4d49d3e3249f
Create Date: 2025-08-11 07:56:00.822962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295f5807dda5'
down_revision: Union[str, None] = '4d49d3e3249f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representatives', sa.Column('user_person_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('representatives_student_person_id_fkey'), 'representatives', type_='foreignkey')
    op.create_foreign_key(None, 'representatives', 'persons', ['user_person_id'], ['person_id'], ondelete='CASCADE')
    op.drop_column('representatives', 'student_person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('representatives', sa.Column('student_person_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'representatives', type_='foreignkey')
    op.create_foreign_key(op.f('representatives_student_person_id_fkey'), 'representatives', 'persons', ['student_person_id'], ['person_id'], ondelete='CASCADE')
    op.drop_column('representatives', 'user_person_id')
    # ### end Alembic commands ###
