"""db(migrations): adjust nullability of database fields

Revision ID: 4a42ea790c5b
Revises: 0125a9c6b159
Create Date: 2025-07-05 16:09:00.104189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a42ea790c5b'
down_revision: Union[str, None] = '0125a9c6b159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'national_id_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('persons', 'national_id_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
