"""db(migrations): create tables for student logic and related entities

Revision ID: 4c04f8970890
Revises: 4a42ea790c5b
Create Date: 2025-08-04 17:57:17.139531

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c04f8970890'
down_revision: Union[str, None] = '4a42ea790c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('city_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ID_CARD', 'PARENT_AUTHORIZATION', 'ENROLMENT_FORM', name='document_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('educational_institutions',
    sa.Column('institution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_affiliated', sa.Boolean(), nullable=False),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_table('students',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='blood_type_enum'), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender_enum'), nullable=False),
    sa.Column('enrolment_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('student_enrolments',
    sa.Column('enrolment_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.Date(), nullable=False),
    sa.Column('unenrolled_at', sa.Date(), nullable=True),
    sa.Column('user_person_id', sa.UUID(), nullable=True),
    sa.Column('student_person_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['educational_institutions.institution_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_person_id'], ['students.person_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_person_id'], ['users.person_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('enrolment_id')
    )
    op.create_table('student_documents',
    sa.Column('enrolment_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='status_type_enum'), nullable=False),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrolment_id'], ['student_enrolments.enrolment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrolment_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_documents')
    op.drop_table('student_enrolments')
    op.drop_table('students')
    op.drop_table('educational_institutions')
    op.drop_table('documents')
    op.drop_table('cities')
    # ### end Alembic commands ###
