"""db(migrations): create table for educational representative history

Revision ID: 4d49d3e3249f
Revises: 4c04f8970890
Create Date: 2025-08-05 00:12:22.889645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d49d3e3249f'
down_revision: Union[str, None] = '4c04f8970890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representatives',
    sa.Column('student_person_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('unassigned_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['educational_institutions.institution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_person_id'], ['persons.person_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_person_id', 'institution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representatives')
    # ### end Alembic commands ###
