"""db(migrations): add representative photo field to educational_institutions

Revision ID: a0d3b8a5a18e
Revises: 25e36f4fe265
Create Date: 2025-09-29 07:19:39.821615

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0d3b8a5a18e'
down_revision: Union[str, None] = '25e36f4fe265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educational_institutions', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gender', if_exists=True)
    # ### end Alembic commands ###
