"""db(migrations): add affiliation field and fix composite PK in representatives

Revision ID: f79409d27c59
Revises: 295f5807dda5
Create Date: 2025-08-30 02:15:12.047266

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f79409d27c59'
down_revision: Union[str, None] = '295f5807dda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educational_institutions', sa.Column('created_at', sa.Date(), nullable=False))
    
    # Fix composite PK in representatives
    bind = op.get_bind()
    insp = sa.inspect(bind)
    pk = insp.get_pk_constraint('representatives')
    if pk and pk.get('name'):
        op.drop_constraint(pk['name'], 'representatives', type_='primary')
        
    op.create_primary_key(op.f('pk_representatives'), 'representatives', ['user_person_id', 'institution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('educational_institutions', 'created_at')
    
    # Revert composite PK in representatives to previous state
    bind = op.get_bind()
    insp = sa.inspect(bind)
    pk = insp.get_pk_constraint('representatives')
    if pk and pk.get('name'):
        op.drop_constraint(pk['name'], 'representatives', type_='primary')
    # ### end Alembic commands ###
