from datetime import date
from typing import List, Optional, Protocol
from uuid import UUID

from .dto import InstitutionDTO, RepresentativeAssignmentDTO


# Educational institution
class IInstitutionsReader(Protocol):
    async def list_all(self) -> List[InstitutionDTO]: ...
    async def get_by_id(self, institution_id: UUID) -> Optional[InstitutionDTO]: ...
    async def get_by_name(self, name: str) -> Optional[InstitutionDTO]: ...

class IInstitutionsWriter(Protocol):
    async def create(self, name: str, city_id: Optional[int] = None) -> InstitutionDTO: ...
    async def soft_delete(self, institution_id: int) -> bool: ...

# Representatives
class IRepresentativeReader(Protocol):
    async def get_current_assignments(self, person_ids: List[UUID]) -> List[RepresentativeAssignmentDTO]: ...
    
class IRepresentativeWriter(Protocol):
    async def create(self, user_person_id: UUID, institution_id: int, unassigned_at: Optional[date] = None) -> bool: ...
    async def unassign_active(self, user_person_id: UUID) -> bool: ...
    